export { default as About } from './About';
// export { default as Contact } from './Contact';
export { default as Hero } from './Hero';
export { default as Mision } from './Mision';
export { default as Vision } from './Vision';
export { default as CoreCompetencies } from './CoreCompetencies';
export { default as OngoingProject } from './OngoingProject';
export { default as Structures } from './Structures';
export { default as Excellence } from './Excellence';
export { default as Company } from './Company';
export { default as Galery } from './Galery';
export { default as Partner } from './Partner';
export { default as Values } from './Values';
